name: ci-fullstack-workflow

# Ensure the workflow runs on schedule (Sunday at 0:00) and on push to the main branch
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'
  

#Use a matrix strategy to use Node.js versions 16.x and 18.x
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18]

    steps:
      # Check out the code from the repository.
      - name: Checkout code
        uses: actions/checkout@v3
      # Set up a Node.js environment using the specified node version.
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-python@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Install the dependencies.
      - name: Install dependencies
        run: npm install

      # Run the tests.
      - name: Build and Test
        run: npm run build && npm run test

      # Run the linter.
      - name: Run linter
        run: kkinni/CI-FullstackApp/main

      # Send a console message at completion.
      - name: Final message
        run: |
          echo "Hello ${{github.actor}}. You pushed to ${{github.repository}} at $(date)."

        
